# Generated by Django 4.2.6 on 2023-10-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=32)),
                ('target_port', models.IntegerField(default=80)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('local_ipaddr', models.CharField(max_length=32)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.source')),
            ],
        ),
    ]
